services:
  zndraw_md:
    build:
      context: .
    restart: always
    environment:
      - ZNDRAW_URL=your-zndraw-url
      - ZNDRAW_AUTH_TOKEN=your-zndraw-auth-token
    deploy:
      resources:
        limits:
          memory: 5000M
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
